---
- name: Gathering ASG_Facts
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
  - name: Gather ASG_Facts
    ec2_asg_facts:
     tags:
      class: "*"
     region: us-east-1 
    register: asg_facts
     			
  - name: Dump ASG_Facts
    debug: 
     var: asg_facts
