---
- name: Gathering ASG_Facts
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
  - name: Gather ASG_Facts
    ec2_asg_facts:
     tags:
      class: blue
     region: us-east-1 
    register: asg_facts
     			
  - name: Dump ASG_Facts
    debug: 
     var: asg_facts

  - name: Set instance version for blue
    set_fact:
      launch_version: blue
      terminate_version: green
    when:
       asg_facts.results[0].tags.class == "green"      
      
  - name: Set instance version for green
    set_fact:
     launch_version: green
     terminate_version: blue
    when:
       asg_facts.results[0].tags.class == "blue" 
