---
- name: Create EC2 Launch Config
  hosts: localhost
  connection: local
  gather_facts: false
  
  tasks:
   - name: gathering ec2 facts
     ec2_instance_facts:
      filters:
        tag-key: class
        instance-state-name: running
      region: us-east-1
     register: ec2_facts

   - name: Dump ASG_Facts
     debug: 
      var: ec2_facts
