---
- name: Create EC2 Launch Config
  hosts: localhost
  connection: local

  tasks:
  - name: EC2 Launch_Config Create
    ec2_lc:
      name: Ansible_Launch_Config
      image_id: ami-013be31976ca2c322
      instance_type: t2.micro
      key_name: ansible
      security_groups: ['Ansible_Tower']
      region: us-east-1
      
