---
- name: Create EC2 Launch Config
  hosts: localhost
  connection: local
  gather_facts: false
  
  tasks:
   - name: gathering ec2 facts
     ec2_instance_facts:
      filters:
        tag-key: class
      region: us-east-1
     register: ec2_facts


   - name: test green instance
     command: echo green >> /tmp/log
     when:
       ec2_facts.instances[0].tags.class == "green"      
      
   - name: testing blue
     command: echo blue >> /tmp/log
     when:
       ec2_facts.instances[0].tags.class == "blue"
  
