---
- name: Create EC2 Launch Config
  hosts: localhost
  connection: local
  gather_facts: false
  
  tasks:
   - name: gathering ec2 facts
     ec2_instance_facts:
      filters:
        tag-key: class
      region: us-east-1
     register: ec2_facts


   - name: test green instance
     copy:
      content: This is a green instance
      dest: /tmp/log
      force: no
     when:
       ec2_facts.instances[0].tags.class == "green"      
      
   - name: testing blue
     copy:
      content: This is a Blue instance
      dest: /tmp/log
      force: no
     when:
       ec2_facts.instances[0].tags.class == "blue"  
