---
- name: Create EC2 Launch Config
  hosts: localhost
  connection: local
  gather_facts: true
  
  tasks:
   - name: testing green
     command: "echo green >> /tmp/log"
     when:
      ec2_tags.tags.class == "green"
      
      
   - name: testing blue
     command: "echo blue >> /tmp/log"
     when:
      ec2_tags.tags.class == "blue"
